### ISSUE TITLE
Change sass files

### ISSUE THREAD

**Issue by Kostronor** [edvm/django-materialize-css#3]
How would I go about using the sass files instead of the css ones?

Do you have an example of changing a variable in sass (like color theme for example)?

Thanks for your work!

**Comment by edvm** [comment]
@Kostronor Hi!, Seems this package is getting very old, maybe i should remove it, not sure. Regards your question, you will find inside the 'materialize' dir, a static dir. Inside 'materialize/static' you will find a git submodule which is this one:https://github.com/Dogfalo/materialize/tree/79f9c8435b0da7e6f907a54ab3120e5b609d45ee
In that submodule you will find the sass files you are looking for. 
Best,
Emiliano.
